services:

  - type: web
    name: streamvix
    env: node
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: SC_ENABLED
        value: true
      - key: SC_BASE_URL
        value: https://streamingcommunityz.pet
      - key: MFP_URL
        sync: false
      - key: MFP_PSW
        sync: false
